### ISSUE TITLE
Few more packages needed - ubuntu 18.04-LTS (Azure Marketplace)

### ISSUE THREAD

**Issue by jmcalalang** [MattDierick/F5-Networks#11]
Had to add: sudo apt-get install socat conntrack

`..."Could not find following packages: socat conntrack", "\u001b[0mTo install missing packages use:", "", "sudo apt-get install socat conntrack"]}`

Also, cloud images don't have ubuntu as a default user, so an update to the tarball path is sometimes also needed :).

Excellent work!

**Comment by MattDierick** [comment]
Thanks, I faced this new issue few days ago as well.
