### ISSUE TITLE
cryptonice index not created

### ISSUE THREAD

**Issue by palooza77** [MattDierick/F5-Networks#14]
Hello,
the logstash-crypto.json config (only filepath adjusted) isn't generating the index, but no error in logstash debug mode.
i see config is also used in #17, is there any dependencies? (fresh elk installation)

Thank you!

**Comment by MattDierick** [comment]
The index will be created the first you push a JSON file into the folder.
I can make a new export of the njson. Let me check

**Comment by palooza77** [comment]
i'm using the python scanner script and the json output gets copied in that directory.
